### ISSUE TITLE
web-doc: (EPIC) update stripe docs to reflect all new 2.0+ features

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#165]
## Necessary Items
**User Story** 
As a Give user, I want the Give Stripe docs to help me better understand all the options and features available in the Give Stripe Addon so that I can choose what is best for my donation forms.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Stripe Gateways|existing|
|**Current Url:**|`https://givewp.com/documentation/add-ons/stripe-gateway/`|*required*|
|**Google Docs URL**|TBD: I think we'll need a doc for this, since the changes are a lot|*required*|

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] There's a page for Google and Apple Pay
- [x] There's a page for Plaid

To finalize this doc, the following is how the main Stripe Doc should be updated/re-arranged. 
- [x] Change "Connecting to Stripe" to match the setting label; e.g. "Stripe Connection"
- [x] Move the whole "Testing the Stripe Gateway" section to a sub-page
- [x] Make the "API-key based Stripe Integration" section be sub-section of the "Stripe Connection" section.
- [x] Delete the "Integrating Your API Keys in Give" and simplify it to just describe copy/pasting the keys into the fields. 
- [x] Then add the missing Settings: 
  - [x] "Statement Descriptor" (move it up to it's proper order beneath "Stripe Connection"
  - [x] 3D Secure Payments
  - [x] "Collecting Billing Details"
  - [x] "Preapprove Only"
  - [x] "Enable ApplePay/Google Pay" (make it simple and just link to the sub-doc)
  - [x] "Enable Stripe Checkout" (change the existing heading "Stripe Modal Checkout")
  - [x] "Credit Card Fields Format" (this one should have a screenshot to illustrate the difference).

**Comment by Benunc** [comment]
Today I published this doc (edits welcomed) https://givewp.com/documentation/add-ons/stripe-gateway/stripe-apple-pay-google-pay/

**Comment by Benunc** [comment]
Made some updates to the main doc here. https://givewp.com/documentation/add-ons/stripe-gateway/stripe-apple-pay-google-pay/

**Comment by Benunc** [comment]
Updated the acceptance criteria here. will work on Plaid next

**Comment by mathetos** [comment]
I think we need a little reorganization of the main Stripe page to better reflect the settings screen. I'll update the Acceptance criteria on that soon.

**Comment by Benunc** [comment]
@mathetos did you ever update the acceptance criteria here? From my perspective this is done, but I'll wait for you to make that call.

**Comment by mathetos** [comment]
@Benunc Acceptance criteria has been updated so that the main Stripe doc will be complete -- each setting of the main Stripe Settings page will have a detailed explanation, and the whole page will follow the same structure as the Stripe Settings page once those items above are completed.

Thanks!

**Comment by Benunc** [comment]
BOOOOOOM.

**Comment by mathetos** [comment]
Ahhhhhh.... this is SOOO much better. Great work!
