### ISSUE TITLE
web-doc: add new donation note doc

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give-docs#188]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/donations/donation-notes
* Doc Title: Donation Notes
* Issue Type: New

## Issue Description

In Give 2.3.0, an admin will able to create two types of notes 
1) Private 
2) Donor note. 

If email configured then the donor will be notified when `Donor note` type note will be added to donation.

This impacts several screens:
* Donation Details (updated screenshot) https://github.com/impress-org/give-docs/issues/195
* Emails (new email type) https://github.com/impress-org/give-docs/issues/196
* Update everywhere the email tags are listed.
* ~Donation History (updated screenshot and explanation)~
* ~A new screen for the Donation Notes screen (this issue is about this screen only)~

This issue is about creating the new sub-page called "Donation Notes" under the existing "Donations" doc. 

## Assets

* [Developer overview video](https://www.useloom.com/share/1b4dabddb0a64fb4a0b79ec745834f7b)

## Related Give Core/Add-on issues

* https://github.com/WordImpress/Give/issues/2159
* https://github.com/impress-org/give-docs/issues/196

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] The Donation Details screen is updated to reflect the new feature.
- [x] The doc has a screenshot of the Donation Note feature
- [x] The doc points to the related Email feature
- [x] The doc explains what happens when the "Note to donor" option is selected in detail, and links to any and all related docs (like the email, email tag)
- [x] The list of email tags is updated to include the {donor_note} tag

**Comment by mathetos** [comment]
I created a new doc for all docs to refer to a complete list of email tags here:
https://givewp.com/documentation/core/settings/emails/email-tags/

I added the `{donor_note}` to that doc.

The other new issues are resolved now as well. This feature is fully documented now.
